FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

# setup timezone
ENV TZ=Europe/Copenhagen
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# install essentials
RUN apt-get update && apt-get install -y curl nano git htop build-essential software-properties-common ca-certificates ffmpeg

# download openfoam and update repos
RUN curl -s https://dl.openfoam.com/add-debian-repo.sh | bash

# install latest openfoam
RUN apt-get update && apt-get install -y openfoam2506-default

# add user "foam"
RUN useradd --user-group --create-home --shell /bin/bash foam ;\
	echo "foam ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    
# source openfoam and fix docker mpi
RUN echo "source /usr/lib/openfoam/openfoam2506/etc/bashrc" >> ~foam/.bashrc ;\
   echo "export OMPI_MCA_btl_vader_single_copy_mechanism=none" >> ~foam/.bashrc

# change environmental variables to make sure $WM_PROJECT_USER_DIR is outside of the container
RUN sed -i '/export WM_PROJECT_USER_DIR=/cexport WM_PROJECT_USER_DIR="/home/foam/foam-$WM_PROJECT_VERSION"' /usr/lib/openfoam/openfoam2506/etc/bashrc

# change user to "foam"
USER foam